language: python
sudo: required
dist: trusty
os:
  - linux
env:
  matrix:
    - VERSION="5.1"   TEST="5.1"   WHAT="lua"
    - VERSION="5.2"   TEST="5.2.2" WHAT="lua"
    - VERSION="5.3"   TEST="5.3.4" WHAT="lua"
    - VERSION="5.2.0" TEST="5.2.0" WHAT="lua"
    - VERSION="5.2.1" TEST="5.2.1" WHAT="lua"
    - VERSION="5.2.2" TEST="5.2.2" WHAT="lua"
    - VERSION="5.3.0" TEST="5.3.0" WHAT="lua"
    - VERSION="5.3.1" TEST="5.3.1" WHAT="lua"
    - VERSION="5.3.2" TEST="5.3.2" WHAT="lua"
    - VERSION="5.3.3" TEST="5.3.3" WHAT="lua"
    - VERSION="5.3.4" TEST="5.3.4" WHAT="lua"
    - VERSION="2.0"   TEST="5.1"   WHAT="luajit"
    - VERSION="2.0"   TEST="5.3.4" WHAT="luajit" COMPAT="5.2"
    - VERSION="2.1"   TEST="5.1"   WHAT="luajit"
    - VERSION="2.1"   TEST="5.3.4" WHAT="luajit" COMPAT="5.2"

install:
  - sudo pip install hererocks
  - sudo hererocks --luarocks=^ $WHAT=$VERSION $COMPAT /usr
  - sudo luarocks make rockspec/environment-master-1.rockspec
  - sudo luarocks make rockspec/coronest-master-1.rockspec
script:
  - /usr/bin/lua test/lua-$TEST.lua

notifications:
  email: false
